// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: LosAngelous/Project/LosController/common/protocal.proto
// Protobuf C++ Version: 5.29.3

#include "protocal.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace los_protocal {

inline constexpr MouseAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        button_{0},
        action_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MouseAction::MouseAction(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MouseActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MouseActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MouseActionDefaultTypeInternal() {}
  union {
    MouseAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MouseActionDefaultTypeInternal _MouseAction_default_instance_;

inline constexpr KeyboardAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : key_code_{0u},
        is_pressed_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR KeyboardAction::KeyboardAction(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct KeyboardActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeyboardActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyboardActionDefaultTypeInternal() {}
  union {
    KeyboardAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyboardActionDefaultTypeInternal _KeyboardAction_default_instance_;

inline constexpr ImageFrame::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        width_{0u},
        height_{0u},
        quality_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ImageFrame::ImageFrame(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ImageFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageFrameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageFrameDefaultTypeInternal() {}
  union {
    ImageFrame _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageFrameDefaultTypeInternal _ImageFrame_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR Heartbeat::Heartbeat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct HeartbeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatDefaultTypeInternal() {}
  union {
    Heartbeat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;

inline constexpr LosMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::los_protocal::Msgtype >(0)},
        sequence_{0u},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR LosMessage::LosMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LosMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LosMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LosMessageDefaultTypeInternal() {}
  union {
    LosMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LosMessageDefaultTypeInternal _LosMessage_default_instance_;
}  // namespace los_protocal
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto = nullptr;
const ::uint32_t
    TableStruct_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::los_protocal::LosMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::los_protocal::LosMessage, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::los_protocal::LosMessage, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::LosMessage, _impl_.sequence_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::los_protocal::LosMessage, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::los_protocal::ImageFrame, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::los_protocal::ImageFrame, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::ImageFrame, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::ImageFrame, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::ImageFrame, _impl_.quality_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::los_protocal::MouseAction, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::los_protocal::MouseAction, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::MouseAction, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::MouseAction, _impl_.button_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::MouseAction, _impl_.action_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::los_protocal::KeyboardAction, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::los_protocal::KeyboardAction, _impl_.key_code_),
        PROTOBUF_FIELD_OFFSET(::los_protocal::KeyboardAction, _impl_.is_pressed_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::los_protocal::Heartbeat, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::los_protocal::LosMessage)},
        {15, -1, -1, sizeof(::los_protocal::ImageFrame)},
        {27, -1, -1, sizeof(::los_protocal::MouseAction)},
        {39, -1, -1, sizeof(::los_protocal::KeyboardAction)},
        {49, -1, -1, sizeof(::los_protocal::Heartbeat)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::los_protocal::_LosMessage_default_instance_._instance,
    &::los_protocal::_ImageFrame_default_instance_._instance,
    &::los_protocal::_MouseAction_default_instance_._instance,
    &::los_protocal::_KeyboardAction_default_instance_._instance,
    &::los_protocal::_Heartbeat_default_instance_._instance,
};
const char descriptor_table_protodef_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n7LosAngelous/Project/LosController/comm"
    "on/protocal.proto\022\014los_protocal\"\231\002\n\nLosM"
    "essage\022#\n\004type\030\001 \001(\0162\025.los_protocal.Msgt"
    "ype\022\020\n\010sequence\030\002 \001(\r\022/\n\013image_frame\030\003 \001"
    "(\0132\030.los_protocal.ImageFrameH\000\0221\n\014mouse_"
    "action\030\004 \001(\0132\031.los_protocal.MouseActionH"
    "\000\0227\n\017keyboard_action\030\005 \001(\0132\034.los_protoca"
    "l.KeyboardActionH\000\022,\n\theartbeat\030\006 \001(\0132\027."
    "los_protocal.HeartbeatH\000B\t\n\007payload\"J\n\nI"
    "mageFrame\022\r\n\005width\030\001 \001(\r\022\016\n\006height\030\002 \001(\r"
    "\022\014\n\004data\030\003 \001(\014\022\017\n\007quality\030\004 \001(\r\"C\n\013Mouse"
    "Action\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\016\n\006button\030\003"
    " \001(\005\022\016\n\006action\030\004 \001(\005\"6\n\016KeyboardAction\022\020"
    "\n\010key_code\030\001 \001(\r\022\022\n\nis_pressed\030\002 \001(\010\"\013\n\t"
    "Heartbeat*<\n\007Msgtype\022\t\n\005IMAGE\020\000\022\t\n\005MOUSE"
    "\020\001\022\014\n\010KEYBOARD\020\002\022\r\n\tHEARTBEAT\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto = {
    false,
    false,
    639,
    descriptor_table_protodef_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
    "LosAngelous/Project/LosController/common/protocal.proto",
    &descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto::offsets,
    file_level_enum_descriptors_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
    file_level_service_descriptors_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
};
namespace los_protocal {
const ::google::protobuf::EnumDescriptor* Msgtype_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto);
  return file_level_enum_descriptors_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Msgtype_internal_data_[] = {
    262144u, 0u, };
bool Msgtype_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class LosMessage::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::los_protocal::LosMessage, _impl_._oneof_case_);
};

void LosMessage::set_allocated_image_frame(::los_protocal::ImageFrame* image_frame) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (image_frame) {
    ::google::protobuf::Arena* submessage_arena = image_frame->GetArena();
    if (message_arena != submessage_arena) {
      image_frame = ::google::protobuf::internal::GetOwnedMessage(message_arena, image_frame, submessage_arena);
    }
    set_has_image_frame();
    _impl_.payload_.image_frame_ = image_frame;
  }
  // @@protoc_insertion_point(field_set_allocated:los_protocal.LosMessage.image_frame)
}
void LosMessage::set_allocated_mouse_action(::los_protocal::MouseAction* mouse_action) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (mouse_action) {
    ::google::protobuf::Arena* submessage_arena = mouse_action->GetArena();
    if (message_arena != submessage_arena) {
      mouse_action = ::google::protobuf::internal::GetOwnedMessage(message_arena, mouse_action, submessage_arena);
    }
    set_has_mouse_action();
    _impl_.payload_.mouse_action_ = mouse_action;
  }
  // @@protoc_insertion_point(field_set_allocated:los_protocal.LosMessage.mouse_action)
}
void LosMessage::set_allocated_keyboard_action(::los_protocal::KeyboardAction* keyboard_action) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (keyboard_action) {
    ::google::protobuf::Arena* submessage_arena = keyboard_action->GetArena();
    if (message_arena != submessage_arena) {
      keyboard_action = ::google::protobuf::internal::GetOwnedMessage(message_arena, keyboard_action, submessage_arena);
    }
    set_has_keyboard_action();
    _impl_.payload_.keyboard_action_ = keyboard_action;
  }
  // @@protoc_insertion_point(field_set_allocated:los_protocal.LosMessage.keyboard_action)
}
void LosMessage::set_allocated_heartbeat(::los_protocal::Heartbeat* heartbeat) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (heartbeat) {
    ::google::protobuf::Arena* submessage_arena = heartbeat->GetArena();
    if (message_arena != submessage_arena) {
      heartbeat = ::google::protobuf::internal::GetOwnedMessage(message_arena, heartbeat, submessage_arena);
    }
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_set_allocated:los_protocal.LosMessage.heartbeat)
}
LosMessage::LosMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:los_protocal.LosMessage)
}
inline PROTOBUF_NDEBUG_INLINE LosMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::los_protocal::LosMessage& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

LosMessage::LosMessage(
    ::google::protobuf::Arena* arena,
    const LosMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LosMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, sequence_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::sequence_));
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kImageFrame:
        _impl_.payload_.image_frame_ = ::google::protobuf::Message::CopyConstruct<::los_protocal::ImageFrame>(arena, *from._impl_.payload_.image_frame_);
        break;
      case kMouseAction:
        _impl_.payload_.mouse_action_ = ::google::protobuf::Message::CopyConstruct<::los_protocal::MouseAction>(arena, *from._impl_.payload_.mouse_action_);
        break;
      case kKeyboardAction:
        _impl_.payload_.keyboard_action_ = ::google::protobuf::Message::CopyConstruct<::los_protocal::KeyboardAction>(arena, *from._impl_.payload_.keyboard_action_);
        break;
      case kHeartbeat:
        _impl_.payload_.heartbeat_ = ::google::protobuf::Message::CopyConstruct<::los_protocal::Heartbeat>(arena, *from._impl_.payload_.heartbeat_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:los_protocal.LosMessage)
}
inline PROTOBUF_NDEBUG_INLINE LosMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void LosMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, sequence_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::sequence_));
}
LosMessage::~LosMessage() {
  // @@protoc_insertion_point(destructor:los_protocal.LosMessage)
  SharedDtor(*this);
}
inline void LosMessage::SharedDtor(MessageLite& self) {
  LosMessage& this_ = static_cast<LosMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void LosMessage::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:los_protocal.LosMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kImageFrame: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.image_frame_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.image_frame_);
      }
      break;
    }
    case kMouseAction: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.mouse_action_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.mouse_action_);
      }
      break;
    }
    case kKeyboardAction: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.keyboard_action_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.keyboard_action_);
      }
      break;
    }
    case kHeartbeat: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.heartbeat_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.heartbeat_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* LosMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LosMessage(arena);
}
constexpr auto LosMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LosMessage),
                                            alignof(LosMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LosMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LosMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LosMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LosMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LosMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LosMessage>(), &LosMessage::ByteSizeLong,
            &LosMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LosMessage, _impl_._cached_size_),
        false,
    },
    &LosMessage::kDescriptorMethods,
    &descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LosMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 6, 4, 0, 2> LosMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::los_protocal::LosMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 sequence = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LosMessage, _impl_.sequence_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.sequence_)}},
    // .los_protocal.Msgtype type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LosMessage, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .los_protocal.Msgtype type = 1;
    {PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint32 sequence = 2;
    {PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.sequence_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .los_protocal.ImageFrame image_frame = 3;
    {PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.payload_.image_frame_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .los_protocal.MouseAction mouse_action = 4;
    {PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.payload_.mouse_action_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .los_protocal.KeyboardAction keyboard_action = 5;
    {PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.payload_.keyboard_action_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .los_protocal.Heartbeat heartbeat = 6;
    {PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.payload_.heartbeat_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::los_protocal::ImageFrame>()},
    {::_pbi::TcParser::GetTable<::los_protocal::MouseAction>()},
    {::_pbi::TcParser::GetTable<::los_protocal::KeyboardAction>()},
    {::_pbi::TcParser::GetTable<::los_protocal::Heartbeat>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void LosMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:los_protocal.LosMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.sequence_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.sequence_));
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LosMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LosMessage& this_ = static_cast<const LosMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LosMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LosMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:los_protocal.LosMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .los_protocal.Msgtype type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          // uint32 sequence = 2;
          if (this_._internal_sequence() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_sequence(), target);
          }

          switch (this_.payload_case()) {
            case kImageFrame: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  3, *this_._impl_.payload_.image_frame_, this_._impl_.payload_.image_frame_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kMouseAction: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  4, *this_._impl_.payload_.mouse_action_, this_._impl_.payload_.mouse_action_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kKeyboardAction: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  5, *this_._impl_.payload_.keyboard_action_, this_._impl_.payload_.keyboard_action_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kHeartbeat: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  6, *this_._impl_.payload_.heartbeat_, this_._impl_.payload_.heartbeat_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:los_protocal.LosMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LosMessage::ByteSizeLong(const MessageLite& base) {
          const LosMessage& this_ = static_cast<const LosMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LosMessage::ByteSizeLong() const {
          const LosMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:los_protocal.LosMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .los_protocal.Msgtype type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
            // uint32 sequence = 2;
            if (this_._internal_sequence() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_sequence());
            }
          }
          switch (this_.payload_case()) {
            // .los_protocal.ImageFrame image_frame = 3;
            case kImageFrame: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.image_frame_);
              break;
            }
            // .los_protocal.MouseAction mouse_action = 4;
            case kMouseAction: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.mouse_action_);
              break;
            }
            // .los_protocal.KeyboardAction keyboard_action = 5;
            case kKeyboardAction: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.keyboard_action_);
              break;
            }
            // .los_protocal.Heartbeat heartbeat = 6;
            case kHeartbeat: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.heartbeat_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LosMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LosMessage*>(&to_msg);
  auto& from = static_cast<const LosMessage&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:los_protocal.LosMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_sequence() != 0) {
    _this->_impl_.sequence_ = from._impl_.sequence_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kImageFrame: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.image_frame_ =
              ::google::protobuf::Message::CopyConstruct<::los_protocal::ImageFrame>(arena, *from._impl_.payload_.image_frame_);
        } else {
          _this->_impl_.payload_.image_frame_->MergeFrom(from._internal_image_frame());
        }
        break;
      }
      case kMouseAction: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.mouse_action_ =
              ::google::protobuf::Message::CopyConstruct<::los_protocal::MouseAction>(arena, *from._impl_.payload_.mouse_action_);
        } else {
          _this->_impl_.payload_.mouse_action_->MergeFrom(from._internal_mouse_action());
        }
        break;
      }
      case kKeyboardAction: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.keyboard_action_ =
              ::google::protobuf::Message::CopyConstruct<::los_protocal::KeyboardAction>(arena, *from._impl_.payload_.keyboard_action_);
        } else {
          _this->_impl_.payload_.keyboard_action_->MergeFrom(from._internal_keyboard_action());
        }
        break;
      }
      case kHeartbeat: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.heartbeat_ =
              ::google::protobuf::Message::CopyConstruct<::los_protocal::Heartbeat>(arena, *from._impl_.payload_.heartbeat_);
        } else {
          _this->_impl_.payload_.heartbeat_->MergeFrom(from._internal_heartbeat());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LosMessage::CopyFrom(const LosMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:los_protocal.LosMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LosMessage::InternalSwap(LosMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.sequence_)
      + sizeof(LosMessage::_impl_.sequence_)
      - PROTOBUF_FIELD_OFFSET(LosMessage, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata LosMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ImageFrame::_Internal {
 public:
};

ImageFrame::ImageFrame(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:los_protocal.ImageFrame)
}
inline PROTOBUF_NDEBUG_INLINE ImageFrame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::los_protocal::ImageFrame& from_msg)
      : data_(arena, from.data_),
        _cached_size_{0} {}

ImageFrame::ImageFrame(
    ::google::protobuf::Arena* arena,
    const ImageFrame& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ImageFrame* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, width_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, width_),
           offsetof(Impl_, quality_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::quality_));

  // @@protoc_insertion_point(copy_constructor:los_protocal.ImageFrame)
}
inline PROTOBUF_NDEBUG_INLINE ImageFrame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_(arena),
        _cached_size_{0} {}

inline void ImageFrame::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, width_),
           0,
           offsetof(Impl_, quality_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::quality_));
}
ImageFrame::~ImageFrame() {
  // @@protoc_insertion_point(destructor:los_protocal.ImageFrame)
  SharedDtor(*this);
}
inline void ImageFrame::SharedDtor(MessageLite& self) {
  ImageFrame& this_ = static_cast<ImageFrame&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ImageFrame::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ImageFrame(arena);
}
constexpr auto ImageFrame::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ImageFrame),
                                            alignof(ImageFrame));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ImageFrame::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ImageFrame_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ImageFrame::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ImageFrame>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ImageFrame::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ImageFrame>(), &ImageFrame::ByteSizeLong,
            &ImageFrame::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_._cached_size_),
        false,
    },
    &ImageFrame::kDescriptorMethods,
    &descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ImageFrame::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> ImageFrame::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::los_protocal::ImageFrame>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 quality = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageFrame, _impl_.quality_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.quality_)}},
    // uint32 width = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageFrame, _impl_.width_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.width_)}},
    // uint32 height = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageFrame, _impl_.height_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.height_)}},
    // bytes data = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 width = 1;
    {PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.width_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 height = 2;
    {PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.height_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bytes data = 3;
    {PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint32 quality = 4;
    {PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.quality_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ImageFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:los_protocal.ImageFrame)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.width_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.quality_) -
      reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.quality_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ImageFrame::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ImageFrame& this_ = static_cast<const ImageFrame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ImageFrame::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ImageFrame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:los_protocal.ImageFrame)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 width = 1;
          if (this_._internal_width() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_width(), target);
          }

          // uint32 height = 2;
          if (this_._internal_height() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_height(), target);
          }

          // bytes data = 3;
          if (!this_._internal_data().empty()) {
            const std::string& _s = this_._internal_data();
            target = stream->WriteBytesMaybeAliased(3, _s, target);
          }

          // uint32 quality = 4;
          if (this_._internal_quality() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_quality(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:los_protocal.ImageFrame)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ImageFrame::ByteSizeLong(const MessageLite& base) {
          const ImageFrame& this_ = static_cast<const ImageFrame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ImageFrame::ByteSizeLong() const {
          const ImageFrame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:los_protocal.ImageFrame)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes data = 3;
            if (!this_._internal_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_data());
            }
            // uint32 width = 1;
            if (this_._internal_width() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_width());
            }
            // uint32 height = 2;
            if (this_._internal_height() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_height());
            }
            // uint32 quality = 4;
            if (this_._internal_quality() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_quality());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ImageFrame::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ImageFrame*>(&to_msg);
  auto& from = static_cast<const ImageFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:los_protocal.ImageFrame)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_width() != 0) {
    _this->_impl_.width_ = from._impl_.width_;
  }
  if (from._internal_height() != 0) {
    _this->_impl_.height_ = from._impl_.height_;
  }
  if (from._internal_quality() != 0) {
    _this->_impl_.quality_ = from._impl_.quality_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageFrame::CopyFrom(const ImageFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:los_protocal.ImageFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImageFrame::InternalSwap(ImageFrame* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.quality_)
      + sizeof(ImageFrame::_impl_.quality_)
      - PROTOBUF_FIELD_OFFSET(ImageFrame, _impl_.width_)>(
          reinterpret_cast<char*>(&_impl_.width_),
          reinterpret_cast<char*>(&other->_impl_.width_));
}

::google::protobuf::Metadata ImageFrame::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MouseAction::_Internal {
 public:
};

MouseAction::MouseAction(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:los_protocal.MouseAction)
}
MouseAction::MouseAction(
    ::google::protobuf::Arena* arena, const MouseAction& from)
    : MouseAction(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MouseAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MouseAction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, action_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::action_));
}
MouseAction::~MouseAction() {
  // @@protoc_insertion_point(destructor:los_protocal.MouseAction)
  SharedDtor(*this);
}
inline void MouseAction::SharedDtor(MessageLite& self) {
  MouseAction& this_ = static_cast<MouseAction&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* MouseAction::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MouseAction(arena);
}
constexpr auto MouseAction::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MouseAction),
                                            alignof(MouseAction));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MouseAction::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MouseAction_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MouseAction::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MouseAction>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MouseAction::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MouseAction>(), &MouseAction::ByteSizeLong,
            &MouseAction::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MouseAction, _impl_._cached_size_),
        false,
    },
    &MouseAction::kDescriptorMethods,
    &descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MouseAction::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> MouseAction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::los_protocal::MouseAction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 action = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseAction, _impl_.action_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.action_)}},
    // int32 x = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseAction, _impl_.x_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.x_)}},
    // int32 y = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseAction, _impl_.y_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.y_)}},
    // int32 button = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseAction, _impl_.button_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.button_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 x = 1;
    {PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 y = 2;
    {PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 button = 3;
    {PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.button_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 action = 4;
    {PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.action_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MouseAction::Clear() {
// @@protoc_insertion_point(message_clear_start:los_protocal.MouseAction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.action_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.action_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MouseAction::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MouseAction& this_ = static_cast<const MouseAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MouseAction::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MouseAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:los_protocal.MouseAction)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 x = 1;
          if (this_._internal_x() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_x(), target);
          }

          // int32 y = 2;
          if (this_._internal_y() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_y(), target);
          }

          // int32 button = 3;
          if (this_._internal_button() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_button(), target);
          }

          // int32 action = 4;
          if (this_._internal_action() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_action(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:los_protocal.MouseAction)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MouseAction::ByteSizeLong(const MessageLite& base) {
          const MouseAction& this_ = static_cast<const MouseAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MouseAction::ByteSizeLong() const {
          const MouseAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:los_protocal.MouseAction)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 x = 1;
            if (this_._internal_x() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_x());
            }
            // int32 y = 2;
            if (this_._internal_y() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_y());
            }
            // int32 button = 3;
            if (this_._internal_button() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_button());
            }
            // int32 action = 4;
            if (this_._internal_action() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_action());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MouseAction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MouseAction*>(&to_msg);
  auto& from = static_cast<const MouseAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:los_protocal.MouseAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_x() != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (from._internal_y() != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (from._internal_button() != 0) {
    _this->_impl_.button_ = from._impl_.button_;
  }
  if (from._internal_action() != 0) {
    _this->_impl_.action_ = from._impl_.action_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MouseAction::CopyFrom(const MouseAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:los_protocal.MouseAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MouseAction::InternalSwap(MouseAction* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.action_)
      + sizeof(MouseAction::_impl_.action_)
      - PROTOBUF_FIELD_OFFSET(MouseAction, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata MouseAction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class KeyboardAction::_Internal {
 public:
};

KeyboardAction::KeyboardAction(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:los_protocal.KeyboardAction)
}
KeyboardAction::KeyboardAction(
    ::google::protobuf::Arena* arena, const KeyboardAction& from)
    : KeyboardAction(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE KeyboardAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void KeyboardAction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, key_code_),
           0,
           offsetof(Impl_, is_pressed_) -
               offsetof(Impl_, key_code_) +
               sizeof(Impl_::is_pressed_));
}
KeyboardAction::~KeyboardAction() {
  // @@protoc_insertion_point(destructor:los_protocal.KeyboardAction)
  SharedDtor(*this);
}
inline void KeyboardAction::SharedDtor(MessageLite& self) {
  KeyboardAction& this_ = static_cast<KeyboardAction&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* KeyboardAction::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) KeyboardAction(arena);
}
constexpr auto KeyboardAction::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(KeyboardAction),
                                            alignof(KeyboardAction));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull KeyboardAction::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_KeyboardAction_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &KeyboardAction::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<KeyboardAction>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &KeyboardAction::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<KeyboardAction>(), &KeyboardAction::ByteSizeLong,
            &KeyboardAction::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(KeyboardAction, _impl_._cached_size_),
        false,
    },
    &KeyboardAction::kDescriptorMethods,
    &descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* KeyboardAction::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> KeyboardAction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::los_protocal::KeyboardAction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_pressed = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(KeyboardAction, _impl_.is_pressed_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(KeyboardAction, _impl_.is_pressed_)}},
    // uint32 key_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(KeyboardAction, _impl_.key_code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(KeyboardAction, _impl_.key_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 key_code = 1;
    {PROTOBUF_FIELD_OFFSET(KeyboardAction, _impl_.key_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool is_pressed = 2;
    {PROTOBUF_FIELD_OFFSET(KeyboardAction, _impl_.is_pressed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void KeyboardAction::Clear() {
// @@protoc_insertion_point(message_clear_start:los_protocal.KeyboardAction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.key_code_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_pressed_) -
      reinterpret_cast<char*>(&_impl_.key_code_)) + sizeof(_impl_.is_pressed_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* KeyboardAction::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const KeyboardAction& this_ = static_cast<const KeyboardAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* KeyboardAction::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const KeyboardAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:los_protocal.KeyboardAction)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 key_code = 1;
          if (this_._internal_key_code() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_key_code(), target);
          }

          // bool is_pressed = 2;
          if (this_._internal_is_pressed() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_is_pressed(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:los_protocal.KeyboardAction)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t KeyboardAction::ByteSizeLong(const MessageLite& base) {
          const KeyboardAction& this_ = static_cast<const KeyboardAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t KeyboardAction::ByteSizeLong() const {
          const KeyboardAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:los_protocal.KeyboardAction)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint32 key_code = 1;
            if (this_._internal_key_code() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_key_code());
            }
            // bool is_pressed = 2;
            if (this_._internal_is_pressed() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void KeyboardAction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<KeyboardAction*>(&to_msg);
  auto& from = static_cast<const KeyboardAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:los_protocal.KeyboardAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_key_code() != 0) {
    _this->_impl_.key_code_ = from._impl_.key_code_;
  }
  if (from._internal_is_pressed() != 0) {
    _this->_impl_.is_pressed_ = from._impl_.is_pressed_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void KeyboardAction::CopyFrom(const KeyboardAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:los_protocal.KeyboardAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void KeyboardAction::InternalSwap(KeyboardAction* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KeyboardAction, _impl_.is_pressed_)
      + sizeof(KeyboardAction::_impl_.is_pressed_)
      - PROTOBUF_FIELD_OFFSET(KeyboardAction, _impl_.key_code_)>(
          reinterpret_cast<char*>(&_impl_.key_code_),
          reinterpret_cast<char*>(&other->_impl_.key_code_));
}

::google::protobuf::Metadata KeyboardAction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Heartbeat::_Internal {
 public:
};

Heartbeat::Heartbeat(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:los_protocal.Heartbeat)
}
Heartbeat::Heartbeat(
    ::google::protobuf::Arena* arena,
    const Heartbeat& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Heartbeat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:los_protocal.Heartbeat)
}

inline void* Heartbeat::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Heartbeat(arena);
}
constexpr auto Heartbeat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Heartbeat),
                                            alignof(Heartbeat));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Heartbeat::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Heartbeat_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Heartbeat::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Heartbeat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Heartbeat::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Heartbeat>(), &Heartbeat::ByteSizeLong,
            &Heartbeat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_._cached_size_),
        false,
    },
    &Heartbeat::kDescriptorMethods,
    &descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Heartbeat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> Heartbeat::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::los_protocal::Heartbeat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata Heartbeat::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace los_protocal
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_LosAngelous_2fProject_2fLosController_2fcommon_2fprotocal_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
