// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocal.proto
// Protobuf C++ Version: 6.33.4

#ifndef protocal_2eproto_2epb_2eh
#define protocal_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protocal_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protocal_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protocal_2eproto;
}  // extern "C"
namespace los_protocal {
enum Msgtype : int;
extern const uint32_t Msgtype_internal_data_[];
class Heartbeat;
struct HeartbeatDefaultTypeInternal;
extern HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Heartbeat_class_data_;
class ImageFrame;
struct ImageFrameDefaultTypeInternal;
extern ImageFrameDefaultTypeInternal _ImageFrame_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ImageFrame_class_data_;
class KeyboardAction;
struct KeyboardActionDefaultTypeInternal;
extern KeyboardActionDefaultTypeInternal _KeyboardAction_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull KeyboardAction_class_data_;
class LosMessage;
struct LosMessageDefaultTypeInternal;
extern LosMessageDefaultTypeInternal _LosMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LosMessage_class_data_;
class MouseAction;
struct MouseActionDefaultTypeInternal;
extern MouseActionDefaultTypeInternal _MouseAction_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MouseAction_class_data_;
}  // namespace los_protocal
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::los_protocal::Msgtype_internal_data_>
    internal::EnumTraitsImpl::value<::los_protocal::Msgtype>;
}  // namespace protobuf
}  // namespace google

namespace los_protocal {
enum Msgtype : int {
  IMAGE = 0,
  MOUSE = 1,
  KEYBOARD = 2,
  HEARTBEAT = 3,
  Msgtype_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Msgtype_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Msgtype_internal_data_[];
inline constexpr Msgtype Msgtype_MIN =
    static_cast<Msgtype>(0);
inline constexpr Msgtype Msgtype_MAX =
    static_cast<Msgtype>(3);
inline bool Msgtype_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int Msgtype_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Msgtype_descriptor();
template <typename T>
const ::std::string& Msgtype_Name(T value) {
  static_assert(::std::is_same<T, Msgtype>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Msgtype_Name().");
  return Msgtype_Name(static_cast<Msgtype>(value));
}
template <>
inline const ::std::string& Msgtype_Name(Msgtype value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Msgtype_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool Msgtype_Parse(
    ::absl::string_view name, Msgtype* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Msgtype>(Msgtype_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class MouseAction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:los_protocal.MouseAction) */ {
 public:
  inline MouseAction() : MouseAction(nullptr) {}
  ~MouseAction() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MouseAction* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MouseAction));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MouseAction(::google::protobuf::internal::ConstantInitialized);

  inline MouseAction(const MouseAction& from) : MouseAction(nullptr, from) {}
  inline MouseAction(MouseAction&& from) noexcept
      : MouseAction(nullptr, ::std::move(from)) {}
  inline MouseAction& operator=(const MouseAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline MouseAction& operator=(MouseAction&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MouseAction& default_instance() {
    return *reinterpret_cast<const MouseAction*>(
        &_MouseAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MouseAction& a, MouseAction& b) { a.Swap(&b); }
  inline void Swap(MouseAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MouseAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MouseAction* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MouseAction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MouseAction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MouseAction& from) { MouseAction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MouseAction* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "los_protocal.MouseAction"; }

  explicit MouseAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MouseAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MouseAction& from);
  MouseAction(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MouseAction&& from) noexcept
      : MouseAction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kButtonFieldNumber = 3,
    kActionFieldNumber = 4,
  };
  // int32 x = 1;
  void clear_x() ;
  ::int32_t x() const;
  void set_x(::int32_t value);

  private:
  ::int32_t _internal_x() const;
  void _internal_set_x(::int32_t value);

  public:
  // int32 y = 2;
  void clear_y() ;
  ::int32_t y() const;
  void set_y(::int32_t value);

  private:
  ::int32_t _internal_y() const;
  void _internal_set_y(::int32_t value);

  public:
  // int32 button = 3;
  void clear_button() ;
  ::int32_t button() const;
  void set_button(::int32_t value);

  private:
  ::int32_t _internal_button() const;
  void _internal_set_button(::int32_t value);

  public:
  // int32 action = 4;
  void clear_action() ;
  ::int32_t action() const;
  void set_action(::int32_t value);

  private:
  ::int32_t _internal_action() const;
  void _internal_set_action(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:los_protocal.MouseAction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MouseAction& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t x_;
    ::int32_t y_;
    ::int32_t button_;
    ::int32_t action_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MouseAction_class_data_;
// -------------------------------------------------------------------

class KeyboardAction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:los_protocal.KeyboardAction) */ {
 public:
  inline KeyboardAction() : KeyboardAction(nullptr) {}
  ~KeyboardAction() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(KeyboardAction* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(KeyboardAction));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR KeyboardAction(::google::protobuf::internal::ConstantInitialized);

  inline KeyboardAction(const KeyboardAction& from) : KeyboardAction(nullptr, from) {}
  inline KeyboardAction(KeyboardAction&& from) noexcept
      : KeyboardAction(nullptr, ::std::move(from)) {}
  inline KeyboardAction& operator=(const KeyboardAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyboardAction& operator=(KeyboardAction&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KeyboardAction& default_instance() {
    return *reinterpret_cast<const KeyboardAction*>(
        &_KeyboardAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(KeyboardAction& a, KeyboardAction& b) { a.Swap(&b); }
  inline void Swap(KeyboardAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyboardAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KeyboardAction* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<KeyboardAction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const KeyboardAction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const KeyboardAction& from) { KeyboardAction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(KeyboardAction* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "los_protocal.KeyboardAction"; }

  explicit KeyboardAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  KeyboardAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const KeyboardAction& from);
  KeyboardAction(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, KeyboardAction&& from) noexcept
      : KeyboardAction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kKeyCodeFieldNumber = 1,
    kIsPressedFieldNumber = 2,
  };
  // uint32 key_code = 1;
  void clear_key_code() ;
  ::uint32_t key_code() const;
  void set_key_code(::uint32_t value);

  private:
  ::uint32_t _internal_key_code() const;
  void _internal_set_key_code(::uint32_t value);

  public:
  // bool is_pressed = 2;
  void clear_is_pressed() ;
  bool is_pressed() const;
  void set_is_pressed(bool value);

  private:
  bool _internal_is_pressed() const;
  void _internal_set_is_pressed(bool value);

  public:
  // @@protoc_insertion_point(class_scope:los_protocal.KeyboardAction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const KeyboardAction& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t key_code_;
    bool is_pressed_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull KeyboardAction_class_data_;
// -------------------------------------------------------------------

class ImageFrame final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:los_protocal.ImageFrame) */ {
 public:
  inline ImageFrame() : ImageFrame(nullptr) {}
  ~ImageFrame() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImageFrame* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImageFrame));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImageFrame(::google::protobuf::internal::ConstantInitialized);

  inline ImageFrame(const ImageFrame& from) : ImageFrame(nullptr, from) {}
  inline ImageFrame(ImageFrame&& from) noexcept
      : ImageFrame(nullptr, ::std::move(from)) {}
  inline ImageFrame& operator=(const ImageFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageFrame& operator=(ImageFrame&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageFrame& default_instance() {
    return *reinterpret_cast<const ImageFrame*>(
        &_ImageFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ImageFrame& a, ImageFrame& b) { a.Swap(&b); }
  inline void Swap(ImageFrame* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageFrame* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageFrame* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImageFrame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImageFrame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImageFrame& from) { ImageFrame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImageFrame* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "los_protocal.ImageFrame"; }

  explicit ImageFrame(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ImageFrame(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ImageFrame& from);
  ImageFrame(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ImageFrame&& from) noexcept
      : ImageFrame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 3,
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
    kQualityFieldNumber = 4,
  };
  // bytes data = 3;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // uint32 width = 1;
  void clear_width() ;
  ::uint32_t width() const;
  void set_width(::uint32_t value);

  private:
  ::uint32_t _internal_width() const;
  void _internal_set_width(::uint32_t value);

  public:
  // uint32 height = 2;
  void clear_height() ;
  ::uint32_t height() const;
  void set_height(::uint32_t value);

  private:
  ::uint32_t _internal_height() const;
  void _internal_set_height(::uint32_t value);

  public:
  // uint32 quality = 4;
  void clear_quality() ;
  ::uint32_t quality() const;
  void set_quality(::uint32_t value);

  private:
  ::uint32_t _internal_quality() const;
  void _internal_set_quality(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:los_protocal.ImageFrame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ImageFrame& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::uint32_t width_;
    ::uint32_t height_;
    ::uint32_t quality_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ImageFrame_class_data_;
// -------------------------------------------------------------------

class Heartbeat final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:los_protocal.Heartbeat) */ {
 public:
  inline Heartbeat() : Heartbeat(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Heartbeat* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Heartbeat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Heartbeat(::google::protobuf::internal::ConstantInitialized);

  inline Heartbeat(const Heartbeat& from) : Heartbeat(nullptr, from) {}
  inline Heartbeat(Heartbeat&& from) noexcept
      : Heartbeat(nullptr, ::std::move(from)) {}
  inline Heartbeat& operator=(const Heartbeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heartbeat& operator=(Heartbeat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Heartbeat& default_instance() {
    return *reinterpret_cast<const Heartbeat*>(
        &_Heartbeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Heartbeat& a, Heartbeat& b) { a.Swap(&b); }
  inline void Swap(Heartbeat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heartbeat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Heartbeat* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<Heartbeat>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Heartbeat& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Heartbeat& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "los_protocal.Heartbeat"; }

  explicit Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Heartbeat& from);
  Heartbeat(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Heartbeat&& from) noexcept
      : Heartbeat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:los_protocal.Heartbeat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_protocal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Heartbeat_class_data_;
// -------------------------------------------------------------------

class LosMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:los_protocal.LosMessage) */ {
 public:
  inline LosMessage() : LosMessage(nullptr) {}
  ~LosMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LosMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LosMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LosMessage(::google::protobuf::internal::ConstantInitialized);

  inline LosMessage(const LosMessage& from) : LosMessage(nullptr, from) {}
  inline LosMessage(LosMessage&& from) noexcept
      : LosMessage(nullptr, ::std::move(from)) {}
  inline LosMessage& operator=(const LosMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline LosMessage& operator=(LosMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LosMessage& default_instance() {
    return *reinterpret_cast<const LosMessage*>(
        &_LosMessage_default_instance_);
  }
  enum PayloadCase {
    kImageFrame = 3,
    kMouseAction = 4,
    kKeyboardAction = 5,
    kHeartbeat = 6,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LosMessage& a, LosMessage& b) { a.Swap(&b); }
  inline void Swap(LosMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LosMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LosMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LosMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LosMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LosMessage& from) { LosMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LosMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "los_protocal.LosMessage"; }

  explicit LosMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LosMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LosMessage& from);
  LosMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LosMessage&& from) noexcept
      : LosMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kSequenceFieldNumber = 2,
    kImageFrameFieldNumber = 3,
    kMouseActionFieldNumber = 4,
    kKeyboardActionFieldNumber = 5,
    kHeartbeatFieldNumber = 6,
  };
  // .los_protocal.Msgtype type = 1;
  void clear_type() ;
  ::los_protocal::Msgtype type() const;
  void set_type(::los_protocal::Msgtype value);

  private:
  ::los_protocal::Msgtype _internal_type() const;
  void _internal_set_type(::los_protocal::Msgtype value);

  public:
  // uint32 sequence = 2;
  void clear_sequence() ;
  ::uint32_t sequence() const;
  void set_sequence(::uint32_t value);

  private:
  ::uint32_t _internal_sequence() const;
  void _internal_set_sequence(::uint32_t value);

  public:
  // .los_protocal.ImageFrame image_frame = 3;
  bool has_image_frame() const;
  private:
  bool _internal_has_image_frame() const;

  public:
  void clear_image_frame() ;
  const ::los_protocal::ImageFrame& image_frame() const;
  [[nodiscard]] ::los_protocal::ImageFrame* PROTOBUF_NULLABLE release_image_frame();
  ::los_protocal::ImageFrame* PROTOBUF_NONNULL mutable_image_frame();
  void set_allocated_image_frame(::los_protocal::ImageFrame* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_image_frame(::los_protocal::ImageFrame* PROTOBUF_NULLABLE value);
  ::los_protocal::ImageFrame* PROTOBUF_NULLABLE unsafe_arena_release_image_frame();

  private:
  const ::los_protocal::ImageFrame& _internal_image_frame() const;
  ::los_protocal::ImageFrame* PROTOBUF_NONNULL _internal_mutable_image_frame();

  public:
  // .los_protocal.MouseAction mouse_action = 4;
  bool has_mouse_action() const;
  private:
  bool _internal_has_mouse_action() const;

  public:
  void clear_mouse_action() ;
  const ::los_protocal::MouseAction& mouse_action() const;
  [[nodiscard]] ::los_protocal::MouseAction* PROTOBUF_NULLABLE release_mouse_action();
  ::los_protocal::MouseAction* PROTOBUF_NONNULL mutable_mouse_action();
  void set_allocated_mouse_action(::los_protocal::MouseAction* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_mouse_action(::los_protocal::MouseAction* PROTOBUF_NULLABLE value);
  ::los_protocal::MouseAction* PROTOBUF_NULLABLE unsafe_arena_release_mouse_action();

  private:
  const ::los_protocal::MouseAction& _internal_mouse_action() const;
  ::los_protocal::MouseAction* PROTOBUF_NONNULL _internal_mutable_mouse_action();

  public:
  // .los_protocal.KeyboardAction keyboard_action = 5;
  bool has_keyboard_action() const;
  private:
  bool _internal_has_keyboard_action() const;

  public:
  void clear_keyboard_action() ;
  const ::los_protocal::KeyboardAction& keyboard_action() const;
  [[nodiscard]] ::los_protocal::KeyboardAction* PROTOBUF_NULLABLE release_keyboard_action();
  ::los_protocal::KeyboardAction* PROTOBUF_NONNULL mutable_keyboard_action();
  void set_allocated_keyboard_action(::los_protocal::KeyboardAction* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_keyboard_action(::los_protocal::KeyboardAction* PROTOBUF_NULLABLE value);
  ::los_protocal::KeyboardAction* PROTOBUF_NULLABLE unsafe_arena_release_keyboard_action();

  private:
  const ::los_protocal::KeyboardAction& _internal_keyboard_action() const;
  ::los_protocal::KeyboardAction* PROTOBUF_NONNULL _internal_mutable_keyboard_action();

  public:
  // .los_protocal.Heartbeat heartbeat = 6;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;

  public:
  void clear_heartbeat() ;
  const ::los_protocal::Heartbeat& heartbeat() const;
  [[nodiscard]] ::los_protocal::Heartbeat* PROTOBUF_NULLABLE release_heartbeat();
  ::los_protocal::Heartbeat* PROTOBUF_NONNULL mutable_heartbeat();
  void set_allocated_heartbeat(::los_protocal::Heartbeat* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_heartbeat(::los_protocal::Heartbeat* PROTOBUF_NULLABLE value);
  ::los_protocal::Heartbeat* PROTOBUF_NULLABLE unsafe_arena_release_heartbeat();

  private:
  const ::los_protocal::Heartbeat& _internal_heartbeat() const;
  ::los_protocal::Heartbeat* PROTOBUF_NONNULL _internal_mutable_heartbeat();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:los_protocal.LosMessage)
 private:
  class _Internal;
  void set_has_image_frame();
  void set_has_mouse_action();
  void set_has_keyboard_action();
  void set_has_heartbeat();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 6,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LosMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int type_;
    ::uint32_t sequence_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE image_frame_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE mouse_action_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE keyboard_action_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE heartbeat_;
    } payload_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LosMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LosMessage

// .los_protocal.Msgtype type = 1;
inline void LosMessage::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::los_protocal::Msgtype LosMessage::type() const {
  // @@protoc_insertion_point(field_get:los_protocal.LosMessage.type)
  return _internal_type();
}
inline void LosMessage::set_type(::los_protocal::Msgtype value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:los_protocal.LosMessage.type)
}
inline ::los_protocal::Msgtype LosMessage::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::los_protocal::Msgtype>(_impl_.type_);
}
inline void LosMessage::_internal_set_type(::los_protocal::Msgtype value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// uint32 sequence = 2;
inline void LosMessage::clear_sequence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t LosMessage::sequence() const {
  // @@protoc_insertion_point(field_get:los_protocal.LosMessage.sequence)
  return _internal_sequence();
}
inline void LosMessage::set_sequence(::uint32_t value) {
  _internal_set_sequence(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:los_protocal.LosMessage.sequence)
}
inline ::uint32_t LosMessage::_internal_sequence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_;
}
inline void LosMessage::_internal_set_sequence(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_ = value;
}

// .los_protocal.ImageFrame image_frame = 3;
inline bool LosMessage::has_image_frame() const {
  return payload_case() == kImageFrame;
}
inline bool LosMessage::_internal_has_image_frame() const {
  return payload_case() == kImageFrame;
}
inline void LosMessage::set_has_image_frame() {
  _impl_._oneof_case_[0] = kImageFrame;
}
inline void LosMessage::clear_image_frame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kImageFrame) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.image_frame_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.image_frame_);
    }
    clear_has_payload();
  }
}
inline ::los_protocal::ImageFrame* PROTOBUF_NULLABLE LosMessage::release_image_frame() {
  // @@protoc_insertion_point(field_release:los_protocal.LosMessage.image_frame)
  if (payload_case() == kImageFrame) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::ImageFrame*>(_impl_.payload_.image_frame_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.image_frame_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::los_protocal::ImageFrame& LosMessage::_internal_image_frame() const {
  return payload_case() == kImageFrame ? static_cast<const ::los_protocal::ImageFrame&>(*reinterpret_cast<::los_protocal::ImageFrame*>(_impl_.payload_.image_frame_))
                     : reinterpret_cast<const ::los_protocal::ImageFrame&>(::los_protocal::_ImageFrame_default_instance_);
}
inline const ::los_protocal::ImageFrame& LosMessage::image_frame() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:los_protocal.LosMessage.image_frame)
  return _internal_image_frame();
}
inline ::los_protocal::ImageFrame* PROTOBUF_NULLABLE LosMessage::unsafe_arena_release_image_frame() {
  // @@protoc_insertion_point(field_unsafe_arena_release:los_protocal.LosMessage.image_frame)
  if (payload_case() == kImageFrame) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::ImageFrame*>(_impl_.payload_.image_frame_);
    _impl_.payload_.image_frame_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LosMessage::unsafe_arena_set_allocated_image_frame(
    ::los_protocal::ImageFrame* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_image_frame();
    _impl_.payload_.image_frame_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:los_protocal.LosMessage.image_frame)
}
inline ::los_protocal::ImageFrame* PROTOBUF_NONNULL LosMessage::_internal_mutable_image_frame() {
  if (payload_case() != kImageFrame) {
    clear_payload();
    set_has_image_frame();
    _impl_.payload_.image_frame_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::los_protocal::ImageFrame>(GetArena()));
  }
  return reinterpret_cast<::los_protocal::ImageFrame*>(_impl_.payload_.image_frame_);
}
inline ::los_protocal::ImageFrame* PROTOBUF_NONNULL LosMessage::mutable_image_frame()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::los_protocal::ImageFrame* _msg = _internal_mutable_image_frame();
  // @@protoc_insertion_point(field_mutable:los_protocal.LosMessage.image_frame)
  return _msg;
}

// .los_protocal.MouseAction mouse_action = 4;
inline bool LosMessage::has_mouse_action() const {
  return payload_case() == kMouseAction;
}
inline bool LosMessage::_internal_has_mouse_action() const {
  return payload_case() == kMouseAction;
}
inline void LosMessage::set_has_mouse_action() {
  _impl_._oneof_case_[0] = kMouseAction;
}
inline void LosMessage::clear_mouse_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMouseAction) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.mouse_action_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.mouse_action_);
    }
    clear_has_payload();
  }
}
inline ::los_protocal::MouseAction* PROTOBUF_NULLABLE LosMessage::release_mouse_action() {
  // @@protoc_insertion_point(field_release:los_protocal.LosMessage.mouse_action)
  if (payload_case() == kMouseAction) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::MouseAction*>(_impl_.payload_.mouse_action_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.mouse_action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::los_protocal::MouseAction& LosMessage::_internal_mouse_action() const {
  return payload_case() == kMouseAction ? static_cast<const ::los_protocal::MouseAction&>(*reinterpret_cast<::los_protocal::MouseAction*>(_impl_.payload_.mouse_action_))
                     : reinterpret_cast<const ::los_protocal::MouseAction&>(::los_protocal::_MouseAction_default_instance_);
}
inline const ::los_protocal::MouseAction& LosMessage::mouse_action() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:los_protocal.LosMessage.mouse_action)
  return _internal_mouse_action();
}
inline ::los_protocal::MouseAction* PROTOBUF_NULLABLE LosMessage::unsafe_arena_release_mouse_action() {
  // @@protoc_insertion_point(field_unsafe_arena_release:los_protocal.LosMessage.mouse_action)
  if (payload_case() == kMouseAction) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::MouseAction*>(_impl_.payload_.mouse_action_);
    _impl_.payload_.mouse_action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LosMessage::unsafe_arena_set_allocated_mouse_action(
    ::los_protocal::MouseAction* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_mouse_action();
    _impl_.payload_.mouse_action_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:los_protocal.LosMessage.mouse_action)
}
inline ::los_protocal::MouseAction* PROTOBUF_NONNULL LosMessage::_internal_mutable_mouse_action() {
  if (payload_case() != kMouseAction) {
    clear_payload();
    set_has_mouse_action();
    _impl_.payload_.mouse_action_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::los_protocal::MouseAction>(GetArena()));
  }
  return reinterpret_cast<::los_protocal::MouseAction*>(_impl_.payload_.mouse_action_);
}
inline ::los_protocal::MouseAction* PROTOBUF_NONNULL LosMessage::mutable_mouse_action()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::los_protocal::MouseAction* _msg = _internal_mutable_mouse_action();
  // @@protoc_insertion_point(field_mutable:los_protocal.LosMessage.mouse_action)
  return _msg;
}

// .los_protocal.KeyboardAction keyboard_action = 5;
inline bool LosMessage::has_keyboard_action() const {
  return payload_case() == kKeyboardAction;
}
inline bool LosMessage::_internal_has_keyboard_action() const {
  return payload_case() == kKeyboardAction;
}
inline void LosMessage::set_has_keyboard_action() {
  _impl_._oneof_case_[0] = kKeyboardAction;
}
inline void LosMessage::clear_keyboard_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kKeyboardAction) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.keyboard_action_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.keyboard_action_);
    }
    clear_has_payload();
  }
}
inline ::los_protocal::KeyboardAction* PROTOBUF_NULLABLE LosMessage::release_keyboard_action() {
  // @@protoc_insertion_point(field_release:los_protocal.LosMessage.keyboard_action)
  if (payload_case() == kKeyboardAction) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::KeyboardAction*>(_impl_.payload_.keyboard_action_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.keyboard_action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::los_protocal::KeyboardAction& LosMessage::_internal_keyboard_action() const {
  return payload_case() == kKeyboardAction ? static_cast<const ::los_protocal::KeyboardAction&>(*reinterpret_cast<::los_protocal::KeyboardAction*>(_impl_.payload_.keyboard_action_))
                     : reinterpret_cast<const ::los_protocal::KeyboardAction&>(::los_protocal::_KeyboardAction_default_instance_);
}
inline const ::los_protocal::KeyboardAction& LosMessage::keyboard_action() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:los_protocal.LosMessage.keyboard_action)
  return _internal_keyboard_action();
}
inline ::los_protocal::KeyboardAction* PROTOBUF_NULLABLE LosMessage::unsafe_arena_release_keyboard_action() {
  // @@protoc_insertion_point(field_unsafe_arena_release:los_protocal.LosMessage.keyboard_action)
  if (payload_case() == kKeyboardAction) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::KeyboardAction*>(_impl_.payload_.keyboard_action_);
    _impl_.payload_.keyboard_action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LosMessage::unsafe_arena_set_allocated_keyboard_action(
    ::los_protocal::KeyboardAction* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_keyboard_action();
    _impl_.payload_.keyboard_action_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:los_protocal.LosMessage.keyboard_action)
}
inline ::los_protocal::KeyboardAction* PROTOBUF_NONNULL LosMessage::_internal_mutable_keyboard_action() {
  if (payload_case() != kKeyboardAction) {
    clear_payload();
    set_has_keyboard_action();
    _impl_.payload_.keyboard_action_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::los_protocal::KeyboardAction>(GetArena()));
  }
  return reinterpret_cast<::los_protocal::KeyboardAction*>(_impl_.payload_.keyboard_action_);
}
inline ::los_protocal::KeyboardAction* PROTOBUF_NONNULL LosMessage::mutable_keyboard_action()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::los_protocal::KeyboardAction* _msg = _internal_mutable_keyboard_action();
  // @@protoc_insertion_point(field_mutable:los_protocal.LosMessage.keyboard_action)
  return _msg;
}

// .los_protocal.Heartbeat heartbeat = 6;
inline bool LosMessage::has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline bool LosMessage::_internal_has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline void LosMessage::set_has_heartbeat() {
  _impl_._oneof_case_[0] = kHeartbeat;
}
inline void LosMessage::clear_heartbeat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kHeartbeat) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.heartbeat_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.heartbeat_);
    }
    clear_has_payload();
  }
}
inline ::los_protocal::Heartbeat* PROTOBUF_NULLABLE LosMessage::release_heartbeat() {
  // @@protoc_insertion_point(field_release:los_protocal.LosMessage.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::Heartbeat*>(_impl_.payload_.heartbeat_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::los_protocal::Heartbeat& LosMessage::_internal_heartbeat() const {
  return payload_case() == kHeartbeat ? static_cast<const ::los_protocal::Heartbeat&>(*reinterpret_cast<::los_protocal::Heartbeat*>(_impl_.payload_.heartbeat_))
                     : reinterpret_cast<const ::los_protocal::Heartbeat&>(::los_protocal::_Heartbeat_default_instance_);
}
inline const ::los_protocal::Heartbeat& LosMessage::heartbeat() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:los_protocal.LosMessage.heartbeat)
  return _internal_heartbeat();
}
inline ::los_protocal::Heartbeat* PROTOBUF_NULLABLE LosMessage::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:los_protocal.LosMessage.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::los_protocal::Heartbeat*>(_impl_.payload_.heartbeat_);
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LosMessage::unsafe_arena_set_allocated_heartbeat(
    ::los_protocal::Heartbeat* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:los_protocal.LosMessage.heartbeat)
}
inline ::los_protocal::Heartbeat* PROTOBUF_NONNULL LosMessage::_internal_mutable_heartbeat() {
  if (payload_case() != kHeartbeat) {
    clear_payload();
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::los_protocal::Heartbeat>(GetArena()));
  }
  return reinterpret_cast<::los_protocal::Heartbeat*>(_impl_.payload_.heartbeat_);
}
inline ::los_protocal::Heartbeat* PROTOBUF_NONNULL LosMessage::mutable_heartbeat()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::los_protocal::Heartbeat* _msg = _internal_mutable_heartbeat();
  // @@protoc_insertion_point(field_mutable:los_protocal.LosMessage.heartbeat)
  return _msg;
}

inline bool LosMessage::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void LosMessage::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline LosMessage::PayloadCase LosMessage::payload_case() const {
  return LosMessage::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ImageFrame

// uint32 width = 1;
inline void ImageFrame::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t ImageFrame::width() const {
  // @@protoc_insertion_point(field_get:los_protocal.ImageFrame.width)
  return _internal_width();
}
inline void ImageFrame::set_width(::uint32_t value) {
  _internal_set_width(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:los_protocal.ImageFrame.width)
}
inline ::uint32_t ImageFrame::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void ImageFrame::_internal_set_width(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// uint32 height = 2;
inline void ImageFrame::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t ImageFrame::height() const {
  // @@protoc_insertion_point(field_get:los_protocal.ImageFrame.height)
  return _internal_height();
}
inline void ImageFrame::set_height(::uint32_t value) {
  _internal_set_height(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:los_protocal.ImageFrame.height)
}
inline ::uint32_t ImageFrame::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void ImageFrame::_internal_set_height(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// bytes data = 3;
inline void ImageFrame::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ImageFrame::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:los_protocal.ImageFrame.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ImageFrame::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:los_protocal.ImageFrame.data)
}
inline ::std::string* PROTOBUF_NONNULL ImageFrame::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:los_protocal.ImageFrame.data)
  return _s;
}
inline const ::std::string& ImageFrame::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void ImageFrame::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ImageFrame::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ImageFrame::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:los_protocal.ImageFrame.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void ImageFrame::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:los_protocal.ImageFrame.data)
}

// uint32 quality = 4;
inline void ImageFrame::clear_quality() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quality_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t ImageFrame::quality() const {
  // @@protoc_insertion_point(field_get:los_protocal.ImageFrame.quality)
  return _internal_quality();
}
inline void ImageFrame::set_quality(::uint32_t value) {
  _internal_set_quality(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:los_protocal.ImageFrame.quality)
}
inline ::uint32_t ImageFrame::_internal_quality() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quality_;
}
inline void ImageFrame::_internal_set_quality(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quality_ = value;
}

// -------------------------------------------------------------------

// MouseAction

// int32 x = 1;
inline void MouseAction::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t MouseAction::x() const {
  // @@protoc_insertion_point(field_get:los_protocal.MouseAction.x)
  return _internal_x();
}
inline void MouseAction::set_x(::int32_t value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:los_protocal.MouseAction.x)
}
inline ::int32_t MouseAction::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void MouseAction::_internal_set_x(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// int32 y = 2;
inline void MouseAction::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t MouseAction::y() const {
  // @@protoc_insertion_point(field_get:los_protocal.MouseAction.y)
  return _internal_y();
}
inline void MouseAction::set_y(::int32_t value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:los_protocal.MouseAction.y)
}
inline ::int32_t MouseAction::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void MouseAction::_internal_set_y(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// int32 button = 3;
inline void MouseAction::clear_button() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.button_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t MouseAction::button() const {
  // @@protoc_insertion_point(field_get:los_protocal.MouseAction.button)
  return _internal_button();
}
inline void MouseAction::set_button(::int32_t value) {
  _internal_set_button(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:los_protocal.MouseAction.button)
}
inline ::int32_t MouseAction::_internal_button() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.button_;
}
inline void MouseAction::_internal_set_button(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.button_ = value;
}

// int32 action = 4;
inline void MouseAction::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t MouseAction::action() const {
  // @@protoc_insertion_point(field_get:los_protocal.MouseAction.action)
  return _internal_action();
}
inline void MouseAction::set_action(::int32_t value) {
  _internal_set_action(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:los_protocal.MouseAction.action)
}
inline ::int32_t MouseAction::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.action_;
}
inline void MouseAction::_internal_set_action(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = value;
}

// -------------------------------------------------------------------

// KeyboardAction

// uint32 key_code = 1;
inline void KeyboardAction::clear_key_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_code_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t KeyboardAction::key_code() const {
  // @@protoc_insertion_point(field_get:los_protocal.KeyboardAction.key_code)
  return _internal_key_code();
}
inline void KeyboardAction::set_key_code(::uint32_t value) {
  _internal_set_key_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:los_protocal.KeyboardAction.key_code)
}
inline ::uint32_t KeyboardAction::_internal_key_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_code_;
}
inline void KeyboardAction::_internal_set_key_code(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_code_ = value;
}

// bool is_pressed = 2;
inline void KeyboardAction::clear_is_pressed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_pressed_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool KeyboardAction::is_pressed() const {
  // @@protoc_insertion_point(field_get:los_protocal.KeyboardAction.is_pressed)
  return _internal_is_pressed();
}
inline void KeyboardAction::set_is_pressed(bool value) {
  _internal_set_is_pressed(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:los_protocal.KeyboardAction.is_pressed)
}
inline bool KeyboardAction::_internal_is_pressed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_pressed_;
}
inline void KeyboardAction::_internal_set_is_pressed(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_pressed_ = value;
}

// -------------------------------------------------------------------

// Heartbeat

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace los_protocal


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::los_protocal::Msgtype> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::los_protocal::Msgtype>() {
  return ::los_protocal::Msgtype_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // protocal_2eproto_2epb_2eh
